name: 'sales_dbt'
version: '1.0.0'
config-version: 2

# The dbt Runner rewrites this to its generated profile at run time.
profile: 'sales_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

# Add your model configs here, e.g.:
# models:
#   sales_dbt:
#     staging:
#       +materialized: view
#     marts:
#       +materialized: table
